### ISSUE TITLE
Créer le rapport de Projet

### ISSUE THREAD

**Issue by dawid-ciborowski-vinci** [e-vinci/web2-2023-project-group-29#5]
- [x] Create Project Team Report
- [x] Add Ergonomics Analyses (marketing vision, wireframes...)
- [ ] Add Result Analysis : deviation against planned UC, issues met, advices

**Comment by dawid-ciborowski-vinci** [comment]
**Rapport v1.2**

Ajouté : 
- Objectif du projet
- Mind Map
- Persona
- Axiomes de Morville
- Wireframes
- Lien Github Project
- Lien Repo

**Comment by Omar-Koubai-Vinci** [comment]
fait
