### ISSUE TITLE
Axiome de Morville

### ISSUE THREAD

**Issue by dawid-ciborowski-vinci** [e-vinci/web2-2023-project-group-29#55]

**Comment by dawid-ciborowski-vinci** [comment]
A modifier : 

- Utile : parler du divertissement
- Désirable : - de visuel, + de fonctionnalité (système de progression - XP), innovant
- Crédible : crédible sur le MARCHÉ
- Utilisable : Aventure progressive, optimisé pour le jeu, connexion obligatoire

**Comment by ahmetkusay-demir-vinci** [comment]
Utile :  Aucune modification sera faites.  L'aspect utilitaire de l'expérience. Cela signifie répondre aux besoins et aux objectifs des utilisateurs. Un produit ou un service doit être fonctionnel et servir un but précis pour l'utilisateur. Le divertissement est déjà abordé à la première ligne avec le mot " amusant ".

Désirable : Done

Crédible : Done

Utilisable : Done

**Comment by dawid-ciborowski-vinci** [comment]
Remis pour l'évaluation.
